In [9]:
# Task No 1

In [10]:
import numpy as np

In [11]:
a=np.array([[ 1, 2, 3, 3, 1,]])
b=np.array([[6, 8, 11, 10, 7]])

In [13]:
c=np.concatenate((a,b),axis=0)
c_t = np.transpose(c)
c_t

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [15]:
av=c_t.mean(axis=0)
av

array([2. , 8.4])

In [16]:
# Task No 2

In [17]:
a_centered=c_t-c_t.mean(axis=0)
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [18]:
# Task No 3

In [29]:
a_centered_sp=a_centered.cumprod(axis=1)[:,1]
a_centered_sp

array([ 2.4, -0. ,  2.6,  1.6,  1.4])

In [31]:
a_centered_sp/(int(a_centered_sp.shape[0])-1)

array([ 0.6 , -0.  ,  0.65,  0.4 ,  0.35])

In [32]:
# PANDAS

In [33]:
import pandas as pd

In [34]:
# Task No 1

In [42]:
a= [1, 2, 3]
b=['Тургенев', 'Чехов', 'Островский']
authors = pd.DataFrame({
    "author_id": a,
    "author_name": b
})
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [43]:
book = pd.DataFrame({
    "author_id":[1, 1, 1, 2, 2, 3, 3],
    "book_title": ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
    "price" : [450, 300, 350, 500, 450, 370, 290]
})
book

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

In [49]:
authors_price=pd.merge(authors,book, on='author_id', how='outer')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

In [50]:
# Task No 3-4

In [64]:
authors_price.sort_values(by="price", inplace=True, ascending=False)
authors_price

author_id author_name            book_title  price
3          2       Чехов      Толстый и тонкий    500
0          1    Тургенев           Отцы и дети    450
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
2          1    Тургенев     Дворянское гнездо    350
1          1    Тургенев                 Рудин    300
6          3  Островский  Таланты и поклонники    290

In [67]:
top5=pd.DataFrame(authors_price.loc[:5,:])
top5

author_id author_name        book_title  price
3          2       Чехов  Толстый и тонкий    500
0          1    Тургенев       Отцы и дети    450
4          2       Чехов   Дама с собачкой    450
5          3  Островский             Гроза    370

In [96]:
groupby=authors_price.groupby("author_name")


In [101]:
authors_stat=pd.DataFrame({
    "min_price":groupby["price"].min(),
    "max_price":groupby["price"].max(),
    "mean_price":groupby["price"].mean(),
})

authors_stat

min_price  max_price  mean_price
author_name                                  
Островский         290        370  330.000000
Тургенев           300        450  366.666667
Чехов              450        500  475.000000