In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [2]:
%matplotlib inline
%config InlineBackend.figure_format = 'svg'

In [4]:
a=np.linspace(12,24,12,dtype=np.int16)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 24], dtype=int16)

In [8]:
def all_div(a:int):
    """The function returns the list of all devisors of a"""
    final=[]
    for x in range(1,a+1):
        if a%x==0:
            final.append(x)
    return final
        

In [13]:
l=all_div(12)
l1=all_div(12)
shapes=[]
for x in l:
    for y in l1:
        if y*x==12:
            shapes.append((x,y))
shapes


[(1, 12), (2, 6), (3, 4), (4, 3), (6, 2), (12, 1)]

In [20]:
for point in shapes:
    if point[0]!=1:
        if point[0]!=12:
            print(a.reshape(point[0],point[1]))

[[12 13 14 15 16 17]
 [18 19 20 21 22 24]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 24]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 24]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 24]]


In [23]:
m=all_div(12)
for i in m[:3]:
    print(a.reshape(i,-1))
    

[[12 13 14 15 16 17 18 19 20 21 22 24]]
[[12 13 14 15 16 17]
 [18 19 20 21 22 24]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 24]]


In [24]:
for j in m[4:]:
    print(a.reshape(-1,j))

[[12 13 14 15 16 17]
 [18 19 20 21 22 24]]
[[12 13 14 15 16 17 18 19 20 21 22 24]]


In [26]:
# Question 4 

a.reshape(12,1).ndim

2

In [29]:
b = np.random.randn(3, 4)
b

array([[-0.7851618 ,  0.49160411, -0.57494762,  0.71758427],
       [-1.24704371, -0.68489995,  1.59248256,  0.43481761],
       [-0.24596145, -1.93727077,  0.29276325,  0.75167839]])

In [30]:
bb=b.flatten()
bb

array([-0.7851618 ,  0.49160411, -0.57494762,  0.71758427, -1.24704371,
       -0.68489995,  1.59248256,  0.43481761, -0.24596145, -1.93727077,
        0.29276325,  0.75167839])

In [31]:
# Quest 6 Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [32]:
a.ndim

1

In [38]:
# Question 7 Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?
b=np.array([[i for i in range(20,0,-2)]for j in range(1)])
b.ndim

2

In [44]:
# Question 8

a=np.zeros((3,2))
b=np.ones((2,2))
d = np.concatenate((a, b), axis=0)
d.size

10

In [60]:
# Question 9 
c=np.arange(12)
s=c.reshape(4,3)
At=s.T
B=s.dot(At)
B.shape
# обратное умножение не получится из за отсутствия коммутативного свойства умножения матриц

(4, 4)

In [61]:
# Question 10 Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

np.random.seed(42)
pp=np.random.randint(0,100)
pp

51

In [70]:
# Question 11 Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 

c = np.linspace(0,15,16,dtype=np.int16)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
      dtype=int16)

In [71]:
# Question 12
C=c.reshape(4,4)
C

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]], dtype=int16)

In [79]:
# Question 12
D=C*10+B
D

array([[  5,  24,  43,  62],
       [ 54, 100, 146, 192],
       [103, 176, 249, 322],
       [152, 252, 352, 452]])

In [80]:
r = np.linalg.matrix_rank(D)
r

2

In [81]:
d = np.linalg.det(D)

-7.685903354004529e-25

In [104]:
D_inv=np.linalg.inv(D)
D_inv

array([[ 1.10382344e+13,  5.26315789e-02, -3.31147031e+13,
         2.20764688e+13],
       [-8.46264636e+13,  9.38249922e+13,  6.62294063e+13,
        -7.54279349e+13],
       [ 1.36138224e+14, -1.87649984e+14, -3.31147031e+13,
         8.46264636e+13],
       [-6.25499948e+13,  9.38249922e+13,  0.00000000e+00,
        -3.12749974e+13]])

In [105]:
# Question 13
D_inv[D_inv<0]=0
D_inv[D_inv>0]=1
D_inv

array([[1., 1., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [0., 1., 0., 0.]])

In [106]:
E = np.random.randint(0, 6, (4, 4))
E

array([[1, 3, 4, 0],
       [3, 1, 5, 4],
       [3, 0, 0, 2],
       [2, 1, 3, 3]])

In [122]:
ind=np.where(D_inv==0)
ind[0][0]

0

In [123]:
# Увы дальше не знаю как((